<a href="https://colab.research.google.com/github/nmadhumi/Bostonhousepriceprediction/blob/main/Credit_card_Fraud_Detection_Project_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv(r'C:\Users\user\Downloads\creditcard.csv')
df

Time        V1        V2        V3        V4        V5        V6  \
0          0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1          0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2          1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3          1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4          2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...      ...       ...       ...       ...       ...       ...       ...   
19995  47051  1.254059 -0.786311  0.286283 -0.666334 -0.951138 -0.389992   
19996  47052 -1.883323  0.104475  1.931791 -3.691559 -0.196086  1.630184   
19997  47052  1.184662 -0.216035  0.651774 -0.168070 -0.769154 -0.379905   
19998  47053  0.829086 -0.420209 -0.323887  1.118331 -0.078426 -0.392259   
19999  47054 -0.437949  0.851474  1.291254  1.115927  0.238548  0.530677   

             V7        V8        V9  ...       V21       V22       V23  \
0      0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474   
1     -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288   
2      0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412   
3      0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321   
4      0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458   
...         ...       ...       ...  ...       ...       ...       ...   
19995 -0.560189 -0.024899 -0.790512  ...  0.040335 -0.060404 -0.100546   
19996 -0.391184  1.133396  2.757721  ... -0.134996  0.395790 -0.229124   
19997 -0.482859  0.188342  0.333287  ... -0.058520 -0.224482  0.157778   
19998  0.545886 -0.259599 -0.032113  ...  0.124450 -0.134035 -0.422629   
19999  0.383649  0.379522 -0.255904  ... -0.024795  0.171924 -0.179547   

            V24       V25       V26       V27       V28  Amount  Class  
0      0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1     -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2     -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3     -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4      0.141267 -0.206010  0.502292  0.219422  0.215153   69.99      0  
...         ...       ...       ...       ...       ...     ...    ...  
19995  0.024825  0.457905 -0.304989 -0.008119  0.012787   75.44      0  
19996 -1.004798  0.596717 -0.950903  0.115782 -0.134574    7.74      0  
19997  0.247821 -0.060009  0.908928 -0.066832 -0.005374    0.77      0  
19998 -0.422666  0.719097 -0.303521 -0.031901  0.055239  250.00      0  
19999 -0.333910 -0.137862 -0.214643  0.412898  0.187111   10.28      0  

[20000 rows x 31 columns]

In [ ]:
df['Class'].value_counts()

0    19936
1       64
Name: Class, dtype: int64

In [ ]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()
amount=df['Amount'].values
df['Amount']=sc.fit_transform(amount.reshape(-1,1))

In [ ]:
df

Time        V1        V2        V3        V4        V5        V6  \
0          0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1          0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2          1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3          1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4          2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...      ...       ...       ...       ...       ...       ...       ...   
19995  47051  1.254059 -0.786311  0.286283 -0.666334 -0.951138 -0.389992   
19996  47052 -1.883323  0.104475  1.931791 -3.691559 -0.196086  1.630184   
19997  47052  1.184662 -0.216035  0.651774 -0.168070 -0.769154 -0.379905   
19998  47053  0.829086 -0.420209 -0.323887  1.118331 -0.078426 -0.392259   
19999  47054 -0.437949  0.851474  1.291254  1.115927  0.238548  0.530677   

             V7        V8        V9  ...       V21       V22       V23  \
0      0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474   
1     -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288   
2      0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412   
3      0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321   
4      0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458   
...         ...       ...       ...  ...       ...       ...       ...   
19995 -0.560189 -0.024899 -0.790512  ...  0.040335 -0.060404 -0.100546   
19996 -0.391184  1.133396  2.757721  ... -0.134996  0.395790 -0.229124   
19997 -0.482859  0.188342  0.333287  ... -0.058520 -0.224482  0.157778   
19998  0.545886 -0.259599 -0.032113  ...  0.124450 -0.134035 -0.422629   
19999  0.383649  0.379522 -0.255904  ... -0.024795  0.171924 -0.179547   

            V24       V25       V26       V27       V28    Amount  Class  
0      0.066928  0.128539 -0.189115  0.133558 -0.021053  0.188357      0  
1     -0.339846  0.167170  0.125895 -0.008983  0.014724 -0.368725      0  
2     -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  1.056757      0  
3     -1.175575  0.647376 -0.221929  0.062723  0.061458  0.089324      0  
4      0.141267 -0.206010  0.502292  0.219422  0.215153 -0.113558      0  
...         ...       ...       ...       ...       ...       ...    ...  
19995  0.024825  0.457905 -0.304989 -0.008119  0.012787 -0.092895      0  
19996 -1.004798  0.596717 -0.950903  0.115782 -0.134574 -0.349578      0  
19997  0.247821 -0.060009  0.908928 -0.066832 -0.005374 -0.376004      0  
19998 -0.422666  0.719097 -0.303521 -0.031901  0.055239  0.568946      0  
19999 -0.333910 -0.137862 -0.214643  0.412898  0.187111 -0.339947      0  

[20000 rows x 31 columns]

In [ ]:
df.drop('Time',axis=1,inplace=True)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(19724, 30)

In [ ]:
x=df.iloc[:,:-1]
x

V1        V2        V3        V4        V5        V6        V7  \
0     -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1      1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2     -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3     -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4     -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
...         ...       ...       ...       ...       ...       ...       ...   
19995  1.254059 -0.786311  0.286283 -0.666334 -0.951138 -0.389992 -0.560189   
19996 -1.883323  0.104475  1.931791 -3.691559 -0.196086  1.630184 -0.391184   
19997  1.184662 -0.216035  0.651774 -0.168070 -0.769154 -0.379905 -0.482859   
19998  0.829086 -0.420209 -0.323887  1.118331 -0.078426 -0.392259  0.545886   
19999 -0.437949  0.851474  1.291254  1.115927  0.238548  0.530677  0.383649   

             V8        V9       V10  ...       V20       V21       V22  \
0      0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838   
1      0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672   
2      0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679   
3      0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274   
4     -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278   
...         ...       ...       ...  ...       ...       ...       ...   
19995 -0.024899 -0.790512  0.685111  ...  0.192768  0.040335 -0.060404   
19996  1.133396  2.757721 -2.409296  ... -0.218017 -0.134996  0.395790   
19997  0.188342  0.333287 -0.045893  ... -0.186540 -0.058520 -0.224482   
19998 -0.259599 -0.032113 -0.106574  ...  0.401778  0.124450 -0.134035   
19999  0.379522 -0.255904  0.117787  ...  0.042213 -0.024795  0.171924   

            V23       V24       V25       V26       V27       V28    Amount  
0     -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  0.188357  
1      0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724 -0.368725  
2      0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  1.056757  
3     -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  0.089324  
4     -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153 -0.113558  
...         ...       ...       ...       ...       ...       ...       ...  
19995 -0.100546  0.024825  0.457905 -0.304989 -0.008119  0.012787 -0.092895  
19996 -0.229124 -1.004798  0.596717 -0.950903  0.115782 -0.134574 -0.349578  
19997  0.157778  0.247821 -0.060009  0.908928 -0.066832 -0.005374 -0.376004  
19998 -0.422629 -0.422666  0.719097 -0.303521 -0.031901  0.055239  0.568946  
19999 -0.179547 -0.333910 -0.137862 -0.214643  0.412898  0.187111 -0.339947  

[19724 rows x 29 columns]

In [ ]:
y=df.iloc[:,-1]
y

0        0
1        0
2        0
3        0
4        0
        ..
19995    0
19996    0
19997    0
19998    0
19999    0
Name: Class, Length: 19724, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
x_train.shape

(13806, 29)

In [ ]:
y_train.shape

(13806,)

In [ ]:
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression()
model1.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=model1.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[5900,    1],
       [  15,    2]], dtype=int64)

In [ ]:
accuracy_score(y_test,y_pred)

0.9972963839134843

In [ ]:
#The Accuracy of Logistic regression is 99.72%

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
n=7
KNN=KNeighborsClassifier(n_neighbors=n)
KNN.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [ ]:
y_predK=KNN.predict(x_test)
y_predK

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
accuracy_score(y_test,y_predK)

0.9972963839134843

In [ ]:
#The Accuracy of Kmeans is 99.72%

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
Dt=DecisionTreeClassifier(max_depth = 4, criterion = 'entropy')


In [ ]:
Dt.fit(x_train,y_train)
y_predD=Dt.predict(x_test)
y_predD

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
accuracy_score(y_test,y_predD)

0.9974653599188915

In [ ]:
#The Accuracy of Logistic regression is 99.74%